// Extracts the handful of Hugeicons glyphs Brainverse uses from @iconify-json/hugeicons
// into lib/icons.ts so they are bundled (no runtime Iconify fetch). Run: node scripts/extract-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const json = JSON.parse(readFileSync(require.resolve('@iconify-json/hugeicons/icons.json'), 'utf8'));
const NAMES = [
  // categories, priorities, rails
  'dumbbell-01','restaurant-02','repeat','briefcase-01','flash','clock-01','moon','inbox','checkmark-circle-02',
  // project icon palette (lib/model.ts PROJECT_ICONS)
  'rocket-01','folder-01','home-01','laptop','camera-01','paint-board','book-open-01','airplane-01','favourite','star','money-bag-01','plant-01','music-note-01','shopping-cart-01','user-group','target-01',
  // chrome
  'comment-01','delete-02','calendar-add-01','google','logout-03','cloud-off','arrow-up-right-01','add-01','more-horizontal','download-04','edit-02','user-circle','shield-01',
];
const out = {};
for (const n of NAMES) {
  const ic = json.icons[n] ?? (json.aliases?.[n] ? json.icons[json.aliases[n].parent] : null);
  if (!ic) { console.error('missing icon', n); process.exit(1); }
  out[n] = { body: ic.body, w: ic.width ?? json.width ?? 24, h: ic.height ?? json.height ?? 24 };
}
const ts = `// GENERATED by scripts/extract-icons.mjs from @iconify-json/hugeicons (MIT). Do not edit.
export type IconName = ${NAMES.map(n => `'${n}'`).join(' | ')};
export const ICONS: Record<IconName, { body: string; w: number; h: number }> = ${JSON.stringify(out, null, 1)};
`;
writeFileSync('lib/icons.ts', ts);
console.log('wrote lib/icons.ts with', NAMES.length, 'icons');
